### ISSUE TITLE
Required permissions update

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics-platform.en#10]
Issue in ./help/connections/overview.md

It seems that an additional permission is required, regarding Identity Namespaces. See the error below.
Can you please check?

![image](https://user-images.githubusercontent.com/72991519/172643573-b877e109-1f7f-4da5-9722-f696198ae847.png)

**Comment by MicaPete** [comment]
@angeli-adobe - you are correct. I have added this permission. Thanks!

https://experienceleague.adobe.com/docs/analytics-platform/using/cja-connections/overview.html
