### ISSUE TITLE
Processing rules documentation

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/analytics-platform.en#10]
Issue in ./help/getting-started/cja-aa.md

Document text:
"Processing Rules | For Analytics Data Connector-based datasets, processing rules are still applied."

Request:
We should add a note that data prep capabilities in AEP can also be used as a replacement for processing rules for data going direct to platform. 

https://experienceleague.adobe.com/docs/experience-platform/data-prep/home.html?lang=en

**Comment by MicaPete** [comment]
https://experienceleague.adobe.com/docs/analytics-platform/using/cja-overview/cja-aa.html?lang=en#partial-support

Thanks!
