### ISSUE TITLE
Data Types compatible with CJA

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics-platform.en#11]
Issue in ./help/connections/create-connection.md

The page does not mention the fact that (as far as I know) only certain type of data types are compatible with CJA (string, int and double).
I think it's important, can you please double check and add the info?

**Comment by MicaPete** [comment]
@angeli-adobe - I have directed this question to PM and engineering.

**Comment by MicaPete** [comment]
@angeli-adobe: I added some of Bryan Skelton's comments here: https://experienceleague.adobe.com/docs/analytics-platform/using/cja-connections/create-connection.html?lang=en
and here:
https://experienceleague.adobe.com/docs/analytics-platform/using/cja-dataviews/create-dataview.html?lang=en

**Comment by MicaPete** [comment]
Just found this out: The following data types are supported: `Integer`, `Int`, `Long`, `Double`, `Float`, `Number`, `Short`, `Byte`, `String`, and `Boolean`.
