### ISSUE TITLE
Additional use case for CJA audience sharing

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/analytics-platform.en#13]
Issue in ./help/components/audiences/audiences-overview.md

Another good use case to add is about how CJA audiences can be used to build audiences on historical data.

**Comment by MicaPete** [comment]
@nhecht - will work on this after shutdown.

**Comment by MicaPete** [comment]
@nhecht - I have created a Jira ticket for this: https://jira.corp.adobe.com/browse/AN-310246

We can track this via Jira.
