### ISSUE TITLE
CJA shared audience identities

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/analytics-platform.en#14]
Issue in ./help/components/audiences/publish.md

"Use CJA audiences in Experience Platform
CJA now takes all the namespace and ID combinations from your published audience and streams them into Real-time Customer Profile (RTCP)."

Can detail be added that outlines what identity CJA marks as primary identity when sharing to AEP?
I assume CJA sends the audiences over to AEP with the primary identity set as whatever the primary identity key is set in CJA.

**Comment by MicaPete** [comment]
@nhecht - You are correct. CJA sends the audiences over to AEP with the primary identity set as whatever was selected as the person ID when the connection was configured. I have added this to the doc and it will be published soon. Thanks.
