### ISSUE TITLE
Describe what happens when a user exits a audience

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/analytics-platform.en#15]
Issue in ./help/components/audiences/publish.md

Can a section be added to this documentation that describes what happens when a user is no longer a member of a segment in CJA?

Does a segment exit event get sent to AEP from CJA or how does the user get removed from the segment in AEP?

**Comment by MicaPete** [comment]
@nhecht - I am discussing this with Trevor - ditto on your other question.

**Comment by MicaPete** [comment]
@nhecht - yes, an exit event is sent to AEP from CJA. I've updated the docs. Published soon.
