### ISSUE TITLE
Cross-Device Analytics Likely Does Not Integrate With AEP Identity Service (Or AEP At All)

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/analytics-platform.en#16]
Issue in ./help/getting-started/cja-overview.md

In the section "Comparing CJA and Cross-Device Analytics", it opens with this comment:

> [Cross-Device Analytics](https://experienceleague.adobe.com/docs/analytics/components/cda/overview.html?lang=en) integrates with [Adobe Experience Platform Identity Service](https://experienceleague.adobe.com/docs/experience-platform/identity/home.html?lang=en)...

The next paragraph says:

> Although CJA does not yet integrate with the Co-op or Private identity graphs...

Trevor Paulsen in product management confirmed that Cross-Device Analytics does not, in any way, work with AEP (see conversation below). Please ask the author to re-research this paragraph and to update accordingly.

![image](https://user-images.githubusercontent.com/53830010/174716663-fd66146f-e258-4991-af38-fedce403ea70.png)

**Comment by MicaPete** [comment]
@gigazelle - please rephrase the statement.

**Comment by gigazelle** [comment]
Thanks Jay! This has been addressed. The comparison didn't quite make sense, so I adjusted it to talk about CDA vs CCA, and moved it to the CCA FAQ. The content was also adjusted to be accurate.
