### ISSUE TITLE
What does it means "Adobe Account Manager"?

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics-platform.en#18]
Issue in ./help/connections/cca/overview.md

The point 2. of the section "Enable Cross-Channel Analytics" is a bit confusing for me. What do you mean with "Adobe Account Manager"? 
- the CSM (Customer Success Manager)
- the AE (Account Executive)
- the NSE (Named Support Engineer)?
In my experience there isn't an "Account Manager" role defined in a standard AEP project.

Thanks

**Comment by MicaPete** [comment]
@angeli-adobe: I think we are talking about the Technical Account Manager (TAM) here. I clarified it in the doc.
https://experienceleague.corp.adobe.com/docs/analytics-platform/using/cja-connections/cca/overview.html
