### ISSUE TITLE
Frequency clarification

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/analytics-platform.en#18]
Issue in ./help/components/audiences/publish.md

The document includes the following sentence. In the sentence I need clarification for what is "other intervals" vs. "all refresh frequencies". If "all" refresh frequencies have a limit of 75 or 150 audiences, then what "other" frequencies would there be that would have no maximum.

It would also be good to outline here what intervals are available.

"You can select other refresh intervals. For all refresh frequencies, there is a limit of 75 or 150 audiences, depending on your CJA entitlement. For other intervals, there is no maximum number of audiences."

**Comment by MicaPete** [comment]
@nhecht - I removed that last sentence. I edited the previous sentence a couple of weeks ago, per Trevor, and forgot to remove the last sentence.
https://experienceleague.adobe.com/docs/analytics-platform/using/cja-components/audiences/publish.html
