### ISSUE TITLE
Refresh frequency limitations

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics-platform.en#19]
Issue in ./help/components/audiences/publish.md

Based on the UI, it seems that the limitation of 75/150 audiences is only for the audiences with 4 hours refresh. Instead the documentation states that the limitation is for all frequencies.

Can you please double check?

![image](https://user-images.githubusercontent.com/72991519/192779308-1a022262-4f81-4914-9ba8-d2d19fa95f13.png)

![image](https://user-images.githubusercontent.com/72991519/192779386-3ca90941-fe5b-4b65-bcd1-961c768b13ba.png)

**Comment by MicaPete** [comment]
@angeli-adobe - you are correct, the UI puts those limitations only on the 4-hour frequency. I am publishing that change right now. Thanks!
