### ISSUE TITLE
"Create filter from selection" poor description

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics-platform.en#2]
Issue in ./help/components/filters/create-filters.md

The description reported in the "Create filter from selection" cell is not clear, and the ordered list is not formatted correctly. Can you please give more details, specifying the actions step by step?

Thanks.

**Comment by MicaPete** [comment]
@angeli-adobe - I made some minor changes and am wondering what specifically is not clear to you. Please elaborate. You can re-open this ticket if what I provided is still not clear, thanks.

https://experienceleague.corp.adobe.com/docs/analytics-platform/using/cja-components/cja-filters/create-filters.html

**Comment by angeli-adobe** [comment]
Thanks @MicaPete ! The description is better, but the list is not formatted correctly.

![image](https://user-images.githubusercontent.com/72991519/167362117-7f55946d-2c4c-4ff2-ba44-6ed45039cef2.png)
