### ISSUE TITLE
Add details on what if a corresponding profile does not exist in RTCDP

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/analytics-platform.en#21]
Issue in ./help/components/audiences/publish.md

If a corresponding profile does not exist in RTCDP, will a new profile be created?
Does CJA send the audience data over as pipeline events or a flat file that also goes to data lake?
What identities does CJA send over?
What is chosen as the primary identity?
Does UIS process the CJA messages as well? i.e. can CJA add identities to a profile identity graph through audience sharing?

**Comment by MicaPete** [comment]
The answers are now captured in the FAQs at the bottom of this page:
https://experienceleague.adobe.com/docs/analytics-platform/using/cja-components/audiences/publish.html?lang=en
