### ISSUE TITLE
CJA features not supported in AA

### ISSUE THREAD

**Issue by rmacrae-at-adobe-com** [AdobeDocs/analytics-platform.en#22]
Could we add a section that lists features available in Customer Journey Analytics that are not available in Adobe Analytics?  Users may come to this part of the documentation from the point of view of "if I migrate to, or add CJA, what could I do, that I can't do in AA".

**Comment by MicaPete** [comment]
This is now on our list of things to do. Expect resolution within a month or 2.

**Comment by MicaPete** [comment]
See these pages for a start:
https://experienceleague.adobe.com/docs/analytics-platform/using/cja-overview/cja-overview.html?lang=en

https://experienceleague.adobe.com/docs/analytics-platform/using/cja-dataviews/data-views.html?lang=en

**Comment by MicaPete** [comment]
We have added this section: https://experienceleague.adobe.com/docs/analytics-platform/using/compare-aa-cja/cja-aa-comparison/cja-aa.html?lang=en#cja-features-not-available-in-adobe-analytics
