### ISSUE TITLE
Missing parameter description

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics-platform.en#24]
Issue in ./help/data-views/component-settings/metric-deduplication.md

In the UI there is an additional field, "Value to keep", that is not mentioned in the table. Can you please add it?

Thanks
Alberto

**Comment by MicaPete** [comment]
Thanks for noticing this, @angeli-adobe: I have added this parameter and a description.
https://experienceleague.adobe.com/docs/analytics-platform/using/cja-dataviews/component-settings/metric-deduplication.html

**Comment by angeli-adobe** [comment]
Thanks @MicaPete ! Really appreciated!
