### ISSUE TITLE
Configure metrics in the data view - Sends schema element not correct

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics-platform.en#25]
Issue in ./help/integrations/ajo.md

In the "Configure metrics in the data view" table, the "Sends" schema element is not correct. The right one is: `_experience.customerJourneyManagement.messageDeliveryfeedback.feedbackStatus`

Can you please update the doc?

**Comment by gigazelle** [comment]
This is corrected. Thank you!
