### ISSUE TITLE
Please Add Specificity for Daily, Weekly, and Monthly Refresh Timing

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/analytics-platform.en#26]
Issue in ./help/components/audiences/publish.md

Hello,

For daily, weekly, and monthly...

- What time of day do daily, weekly, and monthly refreshes occur?
- Can the daily, weekly, and monthly time of day refresh be configured by users, possibly by controlling settings at the CJA admin level?
- What day of the week do weekly refreshes occur, and can this also be configured, possibly by controlling settings at the CJA admin level?

Hoping that these details can be added to the FAQ

**Comment by MicaPete** [comment]
@jtwood426 - the answers to your questions have been added to the bottom of the FAQ section. Thanks.

https://experienceleague.adobe.com/docs/analytics-platform/using/cja-components/audiences/publish.html#faq
