### ISSUE TITLE
Component ID prefix

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics-platform.en#27]
Issue in ./help/data-views/component-settings/overview.md

In the `Component ID` "Description/Use case cell worth to mention that, for components created on fields of lookup and profile dataset, the dataset ID is added as a prefix like:
`6297382c5a4e1d1b9c0e85ca._customernamespace.membership.MEMBERSHIP_TIER_DESC`

Speaking with product team, this is designed to guarantee the uniqueness of the componentID. 
However, this behaviour have an impact on re-usability of the projects across different dataviews.

### USE CASE
There a connection (C1) that takes data from a dataset on sandbox (S1). I create a dataview (DV1) with the component:
`xxxxx._customerNamespace.myfield` where xxxxx is the datasetID.

The I have another connection (C2) that takes data from a dataset sandbox (S2). This dataset have the same schema as S1 and I want to create the same component. I create a dataview (DV2) with the component:

`yyyyy._customerNamespace.myfield` where yyyyy is the datasetID on S2

If don't manually change the component ID, I can't reuse a project across DV1 and DV2 because IDs are different.

This is happening only for lookup and profile dataset, not for event dataset.

The reusability of projects across dataviews is quite an important use case for customers, so worth to mention this specific behaviour in the documentation.

**Comment by ridmaur** [comment]
This has been addressed in an update in the documentation. See https://experienceleague.adobe.com/docs/analytics-platform/using/cja-dataviews/component-settings/overview.html
