### ISSUE TITLE
Minor branding note

### ISSUE THREAD

**Issue by antonioatadobe** [AdobeDocs/analytics-platform.en#31]
Issue in ./help/getting-started/cja-overview.md

While looking at a different issue brought up by our Loc vendors, I've noticed that at the top of this page, we are referring to "**Experience Query Services**". The DX Branding Guidelines doc calls for the first instance of this feature to be "**Adobe Experience Platform Query Service**" and secondary uses as **Experience Platform Query Service** or simply **Query Service** (never "Services").

**Comment by MicaPete** [comment]
Thanks Antonio, I made these changes. About to be published...
