### ISSUE TITLE
Data Science Workspace Reference

### ISSUE THREAD

**Issue by StrawberryBe** [AdobeDocs/analytics-platform.en#32]
Issue in ./help/getting-started/cja-overview.md

I don't believe Data Science Workspace is being sold anymore so I am not sure it should be in the documentation like this? Or at least it should have a hint that this has been discontinued?

**Comment by MicaPete** [comment]
Thanks, @StrawberryBe, you are indeed correct. I have removed the reference to DSW.
https://experienceleague.adobe.com/docs/analytics-platform/using/cja-overview/cja-overview.html#other-capabilities-built-on-adobe-experience-platform
