### ISSUE TITLE
Customer Journey Analytics Guide > Evolution from Adobe Analytics - Drawbacks

### ISSUE THREAD

**Issue by carlostnadobe** [AdobeDocs/analytics-platform.en#33]
Issue in ./help/getting-started/aa-to-cja.md

Customer Journey Analytics Guide > Evolution from Adobe Analytics - Drawbacks

Drawbacks to using Experience Platform SDKs

The following Adobe Analytics features or components are not supported:

Bot Filtering
**Geo, Domain, Device Lookups** --> Is this correct? We can now enable GEO and network on the datastream (check screenshot)
Streaming Media Measurement
Livestream or Livestream triggers

![image](https://github.com/AdobeDocs/analytics-platform.en/assets/68998221/23bdd25f-d39d-4dbd-bbdc-19b3c4b9d825)

**Comment by MicaPete** [comment]
Good catch, this has been fixed:
https://experienceleague.adobe.com/docs/analytics-platform/using/compare-aa-cja/aa-to-cja.html#connector-vs-sdk

**Comment by carlostnadobe** [comment]
Thanks, I just noted it has been changed in English only.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MicaPete** [comment]
The change will roll into the other languages shortly.
