### ISSUE TITLE
Fix Modulus Image in Operator Section

### ISSUE THREAD

**Issue by Adobe-BSavage** [AdobeDocs/analytics-platform.en#38]
Issue in ./help/components/calc-metrics/cm-workflow/cm-build-metrics.md

There is a problem with the modulus image used here:
https://camo.githubusercontent.com/daffc73a56529e6ff84e941d184dfff7f06719f17b1cfa9449df79989d648765/68747470733a2f2f737065637472756d2e61646f62652e636f6d2f7374617469632f69636f6e732f776f726b666c6f775f31382f536d6f636b5f4469766964655f31385f4e2e737667

Operator | Divided by (  ) is the default operator, plus there are the +, -, and x operators.
-- | --

The formatting is skewed due to this image issue when viewing the image online.

![documentation update](https://github.com/AdobeDocs/analytics-platform.en/assets/86071961/1155a39f-ab35-4dec-a702-4ab5a51bba0e)

**Comment by MicaPete** [comment]
@Adobe-BSavage  - I am sorry, but I cannot replicate what you are seeing. Here is what I am seeing:
![operator](https://github.com/AdobeDocs/analytics-platform.en/assets/19596669/e3bafb0c-8099-4313-88c0-7a95df71d44e)
