### ISSUE TITLE
Broken ref or computed HTML link

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/analytics-platform.en#39]
Hey team.
please appreciate the following issue in the page: https://experienceleague.adobe.com/en/docs/analytics-platform/using/cja-components/apply-create-metrics

Section: Types of metrics
Item: Calculated metric templates

The following content is displayed:

- An initial string: Calculated metric templates+-------------+ | img-md | +=============+ | w-18 | +-------------+ | 
- Followed by a picture (see the attachment)
- End finally another string: | +-------------+: Adobe-defined metrics that behave similarly to calculated metrics. You can use them as-is in Workspace projects, or save a copy to customize its logic. 

Mind to verify the content?

Thanks,
Alberto

![image](https://github.com/AdobeDocs/analytics-platform.en/assets/100088147/bab96ddb-d941-4015-9bf6-7f3d58d3ad7b)

Issue in ./help/components/apply-create-metrics.md

**Comment by MicaPete** [comment]
@decaroa - this is what I am seeing:
![metrics](https://github.com/AdobeDocs/analytics-platform.en/assets/19596669/3d7e176c-cd2e-4ea6-90a7-32050c51acd8)
