### ISSUE TITLE
Fix the Q&A about the CJA Audience Publishing capability

### ISSUE THREAD

**Issue by immany** [AdobeDocs/analytics-platform.en#41]
Issue in ./help/getting-started/cja-faq.md

Audience Publishing has been released for a long while. We should change the following Q&A.

> Can I share/publish filters from Customer Journey Analytics to Experience Platform Real-Time CDP, or other Experience Cloud applications?
> Not yet, but Adobe is actively working to deliver this capability.

**Comment by MicaPete** [comment]
https://experienceleague.adobe.com/en/docs/analytics-platform/using/cja-overview/cja-faq

Fixed. Thanks for bringing this to our attention.
