### ISSUE TITLE
A4T info to update

### ISSUE THREAD

**Issue by ericthibeault-adobe** [AdobeDocs/analytics-platform.en#42]
Issue in ./help/getting-started/aa-vs-cja/cja-aa.md

I think with recent CJA release, the A4T info should be reviewed entirely.

-Eric

**Comment by MicaPete** [comment]
https://experienceleague.adobe.com/en/docs/analytics-platform/using/compare-aa-cja/cja-aa-comparison/cja-aa#new-support
Thanks!
