### ISSUE TITLE
Edit to the documentation link

### ISSUE THREAD

**Issue by Akonchada** [AdobeDocs/analytics-platform.en#43]
Issue in ./help/connections/combined-dataset.md
https://experienceleague.adobe.com/en/docs/analytics-platform/using/cja-connections/combined-dataset

NOTE:
When customer tried combining their datasets using PersonId columns with the same name "PurchaserId", but different xdm paths to that name, they didn't get a good CJA UI experience, and they had to go back and add a column matching the same xdm path and name before they could query by a common user-id field.

Suggestion:
The documentation quote above is misleading, and the doc should be updated to strongly a preference for a common PersonId xdm path and name across combined-datasets.

**Comment by Akonchada** [comment]
https://experienceleague.adobe.com/en/docs/analytics-platform/using/cja-connections/combined-dataset

**Comment by ridmaur** [comment]
Updated the docs with clearer information. See updated https://experienceleague.adobe.com/en/docs/analytics-platform/using/cja-connections/combined-dataset
