### ISSUE TITLE
Link for "Geosegmentation Dimensions" goes to blank page

### ISSUE THREAD

**Issue by justlee-adobe** [AdobeDocs/analytics-platform.en#48]
Issue in ./help/getting-started/aa-vs-cja/cja-aa.md

Link for "Geosegmentation Dimensions" goes to blank page
The URL is: https://experienceleague.adobe.com/en/docs/experience-platform/datastreams/configure
Produces a blank page for me.

**Comment by MicaPete** [comment]
I am able to see this page, so unfortunately cannot reproduce this error.
![Untitled](https://github.com/user-attachments/assets/30d24910-96f7-4613-b763-d60045abbcfa)
