### ISSUE TITLE
Connection with Profile datasets only

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics-platform.en#5]
Issue in ./help/connections/create-connection.md

Hi, as far as I know, in a connection for CJA you need to have at least 1 event based dataset. I've checked the documentation and it's not mentioned, and the UI also does not prevent you to create a connection with profile dataset only. Can you please check and update the documentation accordingly?

**Comment by MicaPete** [comment]
You are correct, @angeli-adobe - at least one event dataset is needed. I have added this to the documentation.

https://experienceleague.adobe.com/docs/analytics-platform/using/cja-connections/create-connection.html?lang=en

Note that I am still fixing some formatting errors on this page.
