### ISSUE TITLE
Reference to functionality available in 2023

### ISSUE THREAD

**Issue by justlee-adobe** [AdobeDocs/analytics-platform.en#51]
Issue in ./help/technotes/estimate-usage.md

May want to remove or update the information around this Caution blurb.

> This count applies to event data only, not to profile or lookup data. If you have profile and lookup data, the count will be slightly higher. However, there is currently no way to report on profile and lookup data usage in the user interface. This functionality is slated for **_2023_**.

**Comment by MicaPete** [comment]
Thanks you. I removed the date.
https://experienceleague.adobe.com/en/docs/analytics/components/alerts/intellligent-alerts
