### ISSUE TITLE
CJA - Export Dataset availability - ambiguos release status.

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/analytics-platform.en#54]
Hey team,
please appreciate the following about Export Dataset feature:

- This [page ](https://experienceleague.adobe.com/en/docs/analytics-platform/using/cja-usecases/data-export/overview) is reporting the following statement:
"Currently limited release, full release for Customer Journey Analytics customers is expected in June 2024."

- This [linked page](https://experienceleague.adobe.com/en/docs/analytics-platform/using/cja-usecases/data-export/export-datasets) is reporting anything about the limited release.

If the release is actually limited could you please add a "limited availability" label in the linked page?
If not, could you please remove the "limited release" note in the linking page?

Thanks,
Alberto

Issue in ./help/use-cases/data-export/export-datasets.md

**Comment by ridmaur** [comment]
Thanks for pointing this out. Fixed in the docs by removing the limited release note.
