### ISSUE TITLE
Additional question

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics-platform.en#7]
Issue in ./help/connections/cca/faq.md

I was not able to find any reference to the Identity Map. Can CCA use Identity Map fields?

**Comment by MicaPete** [comment]
@gigazelle - can you answer this question about Cross-Channel Analytics?

**Comment by MicaPete** [comment]
@angeli-adobe - I talked to the PM. According to him, CCA cannot currently use identityMap fields. I will add this to the FAQ.
