### ISSUE TITLE
Link to the video needs to be updated

### ISSUE THREAD

**Issue by mugdoor** [AdobeDocs/analytics-platform.en#8]
Issue in ./help/data-views/configure-dataviews.md

The link at the top of the page to a video for attribution settings needs to be changed to:
https://experienceleague.adobe.com/docs/customer-journey-analytics-learn/tutorials/attribution-settings-in-data-views.html?lang=en

This may need to be updated again, as we are working on some video updates for Data Views V2, but for now, please update to the working URL above, as the link currently up there is broken.
Thanks,
Doug Moore

**Comment by MicaPete** [comment]
@mugdoor - I will close this and will add links from your more current videos.
