### ISSUE TITLE
Enable rolling data window details

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics-platform.en#8]
Issue in ./help/connections/create-connection.md

Hi, as far as I can see, the "Enable rolling data window" is a flag. Hence I assume that I can select it or not. 
If not enabled, what is the standard data retention? I can't see any reference in the documentation.

Thanks

**Comment by MicaPete** [comment]
@angeli-adobe - after discussing with PM, I will add this to the documentation: "If you leave the default (unchecked), the retention period will be superseded by the Adobe Experience Platform data retention setting. This defaults to 13 months. However, if you specified 25 months in Experience Platform, CJA will get 25 months of data through backfill. If you deleted 10 of those months in Platform, CJA would retain the remaining 15 months."

**Comment by MicaPete** [comment]
Actually, I added this: "If you leave the default (unchecked), the retention period will be superseded by the Adobe Experience Platform data retention setting. If you have 25 months' worth of data in Experience Platform, CJA will get 25 months of data through backfill. If you deleted 10 of those months in Platform, CJA would retain the remaining 15 months. "

**Comment by angeli-adobe** [comment]
Thanks @MicaPete! It's more clear now.
