### ISSUE TITLE
Missing "Learn More" link

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics-platform.en#9]
Issue in ./help/getting-started/cja-faq.md

In the "Stitching data" table there is a "Learn more" that does not link any resources.

**Comment by MicaPete** [comment]
https://experienceleague.adobe.com/docs/analytics-platform/using/cja-overview/cja-faq.html?lang=en#2.-stitching-data-(cross-channel-analytics)

Thanks for noticing!
