### ISSUE TITLE
Mobile Dashboards are supported, but not mentioned

### ISSUE THREAD

**Issue by sandrolooser** [AdobeDocs/analytics-platform.en#9]
Issue in ./help/getting-started/cja-aa.md

A great new feature in traditional AA is Mobile Scorecards/Dashboards - from what I understand these are fully supported in CJA. But they're missing on the list of supported features...

Best
/sandro

**Comment by MicaPete** [comment]
Thanks you, @sandrolooser - I have added this.
https://experienceleague.adobe.com/docs/analytics-platform/using/cja-overview/cja-aa.html?lang=en
